/**
 * Generates an automatic FAQ interactive panel system
 * based on internal JSON data within the script/HTML attribute.
 * It transforms the internal list into a panel per question.
 */
function initFAQModule() {
    // Wait for DOM to load
    document.addEventListener("DOMContentLoaded", () => {
        // Select target FAQ anchor
        const faqTarget = document.querySelector('.faq-panel');
        if (!faqTarget) return;

        // Retrieve raw JSON data from data attribute
        const rawData = faqTarget.getAttribute('data-faq');
        if (!rawData) return;

        let faqData = [];
        try {
            faqData = JSON.parse(rawData);
        } catch (e) {
            console.error("Error al parsear el JSON de FAQ:", e);
            return;
        }

        // Select the destination container generated by templateReplacer
        const container = faqTarget.querySelector('.faq-container');
        if (!container) return;

        // Render each FAQ item dynamically
        faqData.forEach(item => {
            const faqItem = document.createElement('div');
            faqItem.classList.add('faq-item');

            // Header panel elements (Question)
            const questionBox = document.createElement('div');
            questionBox.classList.add('faq-question-box');

            const questionText = document.createElement('span');
            questionText.classList.add('faq-question-text');
            questionText.innerHTML = item.q; // Supports HTML tags like <b> or <i>

            const arrowIcon = document.createElement('span');
            arrowIcon.classList.add('faq-arrow');
            arrowIcon.textContent = '▼';

            questionBox.appendChild(questionText);
            questionBox.appendChild(arrowIcon);

            // Sliding panel elements Answer
            const answerBox = document.createElement('div');
            answerBox.classList.add('faq-answer-box');

            const answerContent = document.createElement('div');
            answerContent.classList.add('faq-answer-content');
            answerContent.innerHTML = item.a; // Supports HTML tags like <b> or <i>

            answerBox.appendChild(answerContent);

            // Assemble the complete panel item
            faqItem.appendChild(questionBox);
            faqItem.appendChild(answerBox);
            container.appendChild(faqItem);

            // Toggle expansion on click event
            questionBox.addEventListener('click', () => {
                const isOpen = faqItem.classList.contains('active');

                // Close all other open accordion panels
                container.querySelectorAll('.faq-item').forEach(el => {
                    el.classList.remove('active');
                    el.querySelector('.faq-answer-box').style.maxHeight = null;
                });

                // Open the selected panel if it was closed
                if (!isOpen) {
                    faqItem.classList.add('active');
                    answerBox.style.maxHeight = answerContent.scrollHeight + "px";
                }
            });
        });
    });
}

initFAQModule();